# Generated by Django 5.0.3 on 2024-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
