# Generated by Django 5.0.3 on 2024-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
    ]
