# Generated by Django 5.0.3 on 2024-04-03 06:59

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_game_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default-pic.JPG', force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='profile_images/'),
        ),
    ]
