# Generated by Django 5.0.3 on 2024-04-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_game_cover_game_cover_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cover_image_id',
            new_name='cover_id',
        ),
    ]
