# Generated by Django 5.0.3 on 2024-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_cover_image_id_game_cover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='online_coop',
            field=models.BooleanField(default=False),
        ),
    ]
