# Generated by Django 5.0.3 on 2024-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='online_coop',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
